import { ForestType, VillageType } from "../model"

export const MOCKS = {
  2: {
    initialState: {
      board: {
        8: {
          8: {
            type: ForestType.CACAO_1,
          },
        },
        9: {
          9: {
            type: ForestType.MARKET_2,
          },
        },
      },
      currentPlayerId: null,
      deck: [
        ForestType.TEMPLE_6,
        ForestType.CACAO_1,
        ForestType.TEMPLE_6,
        ForestType.GOLD_1,
        ForestType.CACAO_2,
        ForestType.MARKET_2,
        ForestType.CACAO_2,
        ForestType.CACAO_1,
        ForestType.WATER,
        ForestType.SUN_DISK,
        ForestType.GOLD_2,
        ForestType.TEMPLE_6,
        ForestType.WATER,
        ForestType.MARKET_3,
        ForestType.MARKET_4,
        ForestType.TEMPLE_6,
        ForestType.MARKET_3,
        ForestType.MARKET_3,
        ForestType.CACAO_1,
      ],
      over: false,
      playerOrder: ["player1", "player2"],
      players: {
        player1: {
          action: null,
          beans: 0,
          coins: 0,
          deck: [
            VillageType.VILLAGE_3100,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_1111,
          ],
          hand: [
            VillageType.VILLAGE_3001,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_1111,
          ],
          name: "Player 1",
          ready: true,
          sun: 0,
          water: 0,
        },
        player2: {
          action: null,
          beans: 0,
          coins: 0,
          deck: [
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_3100,
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_3001,
          ],
          hand: [
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_1111,
          ],
          name: "Player 2",
          ready: true,
          sun: 0,
          water: 0,
        },
      },
      seed: 0,
      startingPlayerId: "player2",
      tiles: [null, null],
    },
    playerOrder: ["player1", "player2"],
    players: {
      player1: {
        name: "Player 1",
      },
      player2: {
        name: "Player 2",
      },
    },
  },
  3: {
    initialState: {
      board: {
        8: {
          8: {
            type: ForestType.CACAO_1,
          },
        },
        9: {
          9: {
            type: ForestType.MARKET_2,
          },
        },
      },
      currentPlayerId: null,
      deck: [
        ForestType.SUN_DISK,
        ForestType.MARKET_2,
        ForestType.GOLD_1,
        ForestType.CACAO_1,
        ForestType.TEMPLE_6,
        ForestType.WATER,
        ForestType.CACAO_1,
        ForestType.TEMPLE_6,
        ForestType.MARKET_3,
        ForestType.CACAO_1,
        ForestType.MARKET_3,
        ForestType.TEMPLE_6,
        ForestType.CACAO_2,
        ForestType.GOLD_1,
        ForestType.CACAO_2,
        ForestType.TEMPLE_6,
        ForestType.CACAO_1,
        ForestType.GOLD_2,
        ForestType.WATER,
        ForestType.WATER,
        ForestType.MARKET_4,
        ForestType.SUN_DISK,
        ForestType.TEMPLE_6,
        ForestType.MARKET_3,
        ForestType.MARKET_3,
        ForestType.CACAO_1,
      ],
      over: false,
      playerOrder: ["player1", "player2", "player3"],
      players: {
        player1: {
          action: null,
          beans: 0,
          coins: 0,
          deck: [
            VillageType.VILLAGE_3100,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_2101,
          ],
          hand: [
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_3001,
            VillageType.VILLAGE_1111,
          ],
          name: "Player 1",
          ready: true,
          sun: 0,
          water: 0,
        },
        player2: {
          action: null,
          beans: 0,
          coins: 0,
          deck: [
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_3001,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_3100,
          ],
          hand: [
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_1111,
          ],
          name: "Player 2",
          ready: true,
          sun: 0,
          water: 0,
        },
        player3: {
          action: null,
          beans: 0,
          coins: 0,
          deck: [
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_3001,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_3100,
          ],
          hand: [
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_2101,
          ],
          name: "Player 3",
          ready: true,
          sun: 0,
          water: 0,
        },
      },
      seed: 0,
      startingPlayerId: "player3",
      tiles: [null, null],
    },
    playerOrder: ["player1", "player2", "player3"],
    players: {
      player1: {
        name: "Player 1",
      },
      player2: {
        name: "Player 2",
      },
      player3: {
        name: "Player 3",
      },
    },
  },
  4: {
    initialState: {
      board: {
        8: {
          8: {
            type: ForestType.CACAO_1,
          },
        },
        9: {
          9: {
            type: ForestType.MARKET_2,
          },
        },
      },
      currentPlayerId: null,
      deck: [
        ForestType.SUN_DISK,
        ForestType.MARKET_2,
        ForestType.GOLD_1,
        ForestType.CACAO_1,
        ForestType.TEMPLE_6,
        ForestType.WATER,
        ForestType.CACAO_1,
        ForestType.TEMPLE_6,
        ForestType.MARKET_3,
        ForestType.CACAO_1,
        ForestType.MARKET_3,
        ForestType.TEMPLE_6,
        ForestType.CACAO_2,
        ForestType.GOLD_1,
        ForestType.CACAO_2,
        ForestType.TEMPLE_6,
        ForestType.CACAO_1,
        ForestType.GOLD_2,
        ForestType.WATER,
        ForestType.WATER,
        ForestType.MARKET_4,
        ForestType.SUN_DISK,
        ForestType.TEMPLE_6,
        ForestType.MARKET_3,
        ForestType.MARKET_3,
        ForestType.CACAO_1,
      ],
      over: false,
      playerOrder: ["player1", "player2", "player3", "player4"],
      players: {
        player1: {
          action: null,
          beans: 0,
          coins: 0,
          deck: [
            VillageType.VILLAGE_3001,
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_3100,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_2101,
          ],
          hand: [
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_2101,
          ],
          name: "Player 1",
          ready: true,
          sun: 0,
          water: 0,
        },
        player2: {
          action: null,
          beans: 0,
          coins: 0,
          deck: [
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_3001,
            VillageType.VILLAGE_1111,
          ],
          hand: [
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_3100,
          ],
          name: "Player 2",
          ready: true,
          sun: 0,
          water: 0,
        },
        player3: {
          action: null,
          beans: 0,
          coins: 0,
          deck: [
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_3001,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_3100,
          ],
          hand: [
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_2101,
          ],
          name: "Player 3",
          ready: true,
          sun: 0,
          water: 0,
        },
        player4: {
          action: null,
          beans: 0,
          coins: 0,
          deck: [
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_3100,
            VillageType.VILLAGE_1111,
            VillageType.VILLAGE_3001,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_2101,
          ],
          hand: [
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_2101,
            VillageType.VILLAGE_1111,
          ],
          name: "Player 4",
          ready: true,
          sun: 0,
          water: 0,
        },
      },
      seed: 0,
      startingPlayerId: "player4",
      tiles: [null, null],
    },
    playerOrder: ["player1", "player2", "player3", "player4"],
    players: {
      player1: {
        name: "Player 1",
      },
      player2: {
        name: "Player 2",
      },
      player3: {
        name: "Player 3",
      },
      player4: {
        name: "Player 4",
      },
    },
  },
}
