nodeLinker: node-modules

packageExtensions:
  "@mdx-js/loader@*":
    peerDependencies:
      react: "*"
  "@storybook/addon-essentials@*":
    peerDependencies:
      "@storybook/components": "*"
      "@storybook/core-events": "*"
      "@storybook/theming": "*"
  "@storybook/core@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/core-server@*":
    peerDependencies:
      "@babel/core": "*"
  "@storybook/csf-tools@*":
    peerDependencies:
      "@babel/core": "*"
  react-dev-utils@*:
    peerDependencies:
      typescript: "*"
      webpack: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
